version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: nombre_base_datos
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "fsync=off"]

volumes:
  db_data:
